modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/macuguita/branches-arch/issues"
license = "All-Rights-Reserved"

[[mods]]
modId = "branches"
version = "${version}"
displayName = "guita's Branches"
authors = "macuguita"
description = '''
This mod adds branches for better vegetation decoration!
'''
logoFile = "assets/branches/icon.png"

[[dependencies.branches]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.branches]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.branches]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
