modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/macuguita/branches-arch/issues"
license = "All-Rights-Reserved"

[[mods]]
modId = "branches"
version = "${version}"
displayName = "guita's Branches"
authors = "macuguita"
description = '''
This mod adds branches for better vegetation decoration!
'''
logoFile = "assets/branches/icon.png"

[[dependencies.branches]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.branches]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.branches]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.branches]]
modId = "everycomp"
type = "optional"
versionRange = "*"
ordering = "BEFORE"
side = "BOTH"

[[mixins]]
config = "branches.mixins.json"
